services:
  # Generator
  generator:
    build:
      context: ./generator
      dockerfile: Dockerfile
    environment:
      S3_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: rootuser
      AWS_SECRET_ACCESS_KEY: rootpass123
      BRONZE_BUCKET: bronze  
    volumes:
      - dataLakeVolume:/data
    networks:
      - network

  # Cleaner
  cleaner:
    build:
      context: ./cleaner
      dockerfile: Dockerfile
    environment:
      S3_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: rootuser
      AWS_SECRET_ACCESS_KEY: rootpass123
      BRONZE_BUCKET: silver
    volumes:
      - dataLakeVolume:/data
    networks:
      - network

  # Aggregator
  aggregator:
    build:
      context: ./aggregator
      dockerfile: Dockerfile
    environment:
      S3_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: rootuser
      AWS_SECRET_ACCESS_KEY: rootpass123
      BRONZE_BUCKET: gold
    volumes:
      - dataLakeVolume:/data
    networks:
      - network

  # Minio
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: rootuser
      MINIO_ROOT_PASSWORD: rootpass123
      MINIO_REGION: us-east-1
    ports:
      - "9000:9000"   
      - "9001:9001"
    volumes:
      - dataMinio:/data
    command: server /data --console-address ":9001"
    networks:
      - network

  # Minio init (cr√©ation des buckets)
  minio-init:
    build:
      context: ./minio_init
      dockerfile: Dockerfile
    depends_on:
      - minio
    networks:
      - network

volumes:
  dataLakeVolume:
  dataMinio:

networks:
  network:
